Fixed error with Tomcat not being able to find the ConnectorJ library in Java EE (not STS). The problem was that there is a difference between compiling the code in Eclipse and actually deploying a WAR file. The ConnectorJ library was not being added to the WAR file, even though it compiled in Eclipse. To fix this, open the project's Properties and change the settings in "Deployment Assembly" (for Eclipse Helios). The "Web Content/WEB-INF/lib" folder needs to be included in the construction of the WAR file, and deployed in the same location. Doing so changes an internal Eclipse file, which is being included in this commit.
Solution found at:
http://stackoverflow.com/questions/857409/under-tomcat-java-lang-noclassdeffounderror-when-accessing-a-servlet
Specifically:
http://stackoverflow.com/questions/857409/under-tomcat-java-lang-noclassdeffounderror-when-accessing-a-servlet/4409562#4409562
And:
http://stackoverflow.com/questions/857409/under-tomcat-java-lang-noclassdeffounderror-when-accessing-a-servlet/857429#857429

Signed-off-by: smitht <terry@smith>